name: Update & Build

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        env:
          MAX_ITEMS_PER_SOURCE: 50
          MAX_TOTAL_ITEMS: 400
        run: |
          python scripts/update.py

      - name: Upload artifact (optional)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
